### ISSUE TITLE
How i set rotation axis ?

### ISSUE THREAD

**Issue by jonatasfreitasv** [bbecquet/Leaflet.RotatedMarker#1]

**Comment by bbecquet** [comment]
Hi,

If what you're thinking about rotating freely along all the 3d space axes, like the CSS `rotateX/Y/Z()` operations, it's not possible by using this plug-in. It's meant only to rotate marker icons along the axis perpendicular to the map plane (which is actually the Z axis), because this seems to be a rather common use case.

I'm not sure it would make sense to introduce an option to choose another axis, as I think the other two are style-only, easy to achieve with only basic CSS styling of markers.
But maybe I'm wrong. Could you be more precise about what you'd like to do, please?
