### ISSUE TITLE
marker rotates full circle

### ISSUE THREAD

**Issue by MaddyMastering** [bbecquet/Leaflet.RotatedMarker#12]
when angle is set from 5 to 355 , marker moves clockwise so it performs a full circle instead it should have turned anticlockwise so that it can make small turn. how i can do this?

**Comment by bbecquet** [comment]
Hi!
This is not really a part of the plugin, as it doesn't come with any animation, but I guess you added some `transition` property to the marker style.
The direction of the rotation depends only on the start and end angle values. Rotation is clockwise if end > start, and counter-clockwise if start > end. Fortunately, all different values of an angleare supported, not only [0, 360[, but also negatives and all values modulo 360.
That means 355 deg <=> -5 deg, so if you use -5 in your example, the animation will happen counter-clockwise. To generalize it, you need to compute:
 - for clockwise, the minimum value of the end angle greater than the start angle
 - for counter-clockwise, the maximum value of the end angle lower than the start angle

**Comment by dylankolson** [comment]
Would love to be able to set the direction of the rotation

**Comment by bbecquet** [comment]
Hi @diklankolsin. As I explained in the above reply, rotation animation is *not* part of this plug-in, but I proposed a way to control it through angle values. I don't want to give the plug-in responsibility for animation, because more than direction it would open the door to other things that are better left to CSS (rotation speed and easing, for example).
