### ISSUE TITLE
Not working with Leaflet 1.1.0 and 1.2.0

### ISSUE THREAD

**Issue by amir-alic** [bbecquet/Leaflet.RotatedMarker#15]
My original implementation was with Leaflet 1.0.3 and all was OK.

Now I updated to Leaflet 1.2.0 and have exception 

> Cannot read property 'prototype' of undefined
node_modules/leaflet-rotatedmarker/leaflet.rotatedMarker.js:5:44

_Same exception happens with Leaflet 1.1.0._

Can it be updated/fixed so this plugin works with newest Leaflet 1.2.0?

**Comment by bbecquet** [comment]
Hi!
This seems to be a duplicate of issue https://github.com/bbecquet/Leaflet.RotatedMarker/issues/13, which was fixed in version 0.2.0. It concerned only version 1.1.0 at the time but I've tested with version 1.2.0 since and it worked.
You probably need to update the version number you import if you want to use it with Leaflet 1.1.0 or 1.2.0.

**Comment by amir-alic** [comment]
Thanks for the reply, it **is working with the 0.2.0** version. 
I was using 0.1.2 version (of leaflet-rotatedmarker).
